[package]
name = "destroy_ds_store"
author = "Faisal Ahmed"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
clap = "2"
